version: '2.17'

services:
  flask-app:
    container_name: psid-api-container
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../:/psid
    networks:
      - net
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app:create_app('development')
      - FLASK_RUN_HOST=0.0.0.0
      - MONGODB_URL=mongodb://admin:ChangeMe@mongodb:27017/sales
    depends_on:
      - mongodb

  mongodb:
    container_name: database-container
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ChangeMe
    volumes:
      - mongo-data:/data/db
    networks:
      - net

volumes:
  mongo-data:

networks:
  net:
    driver: bridge